version: "3.9"

name: ai-learning-platform

services:
  db:
    image: postgres:15
    container_name: ailearning-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - ai-learning-platform-net
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-learning-platform-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - ai-learning-platform-net
    command: >
      uvicorn backend.main:app
      --host 0.0.0.0
      --port 8000

networks:
  ai-learning-platform-net:
    driver: bridge

volumes:
  pgdata: