"""fix: is_active in  tasks table

Revision ID: 4de1b3a76839
Revises: 44ff06d90018
Create Date: 2026-06-23 12:59:25.669856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de1b3a76839'
down_revision: Union[str, Sequence[str], None] = '44ff06d90018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('class_id', sa.UUID(), nullable=True))
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tasks_class_id'), 'tasks', ['class_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_class_id'), table_name='tasks')
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('tasks', 'class_id')
    # ### end Alembic commands ###
