"""update prompt classification  table

Revision ID: ebc35151e384
Revises: 3ec1223ba6d4
Create Date: 2026-04-03 14:47:39.588804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc35151e384'
down_revision: Union[str, Sequence[str], None] = '3ec1223ba6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_history_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('is_direct_answer', sa.Boolean(), nullable=False),
    sa.Column('is_explanation', sa.Boolean(), nullable=False),
    sa.Column('is_step_by_step', sa.Boolean(), nullable=False),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.Column('is_rewrite', sa.Boolean(), nullable=False),
    sa.Column('is_feedback', sa.Boolean(), nullable=False),
    sa.Column('is_summary', sa.Boolean(), nullable=False),
    sa.Column('is_translation', sa.Boolean(), nullable=False),
    sa.Column('is_brainstorm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_history_id'], ['chat_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_classifications_chat_history_id'), 'prompt_classifications', ['chat_history_id'], unique=True)
    op.create_index(op.f('ix_prompt_classifications_session_id'), 'prompt_classifications', ['session_id'], unique=False)
    op.create_index(op.f('ix_prompt_classifications_student_id'), 'prompt_classifications', ['student_id'], unique=False)
    op.create_index(op.f('ix_prompt_classifications_task_id'), 'prompt_classifications', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_classifications_task_id'), table_name='prompt_classifications')
    op.drop_index(op.f('ix_prompt_classifications_student_id'), table_name='prompt_classifications')
    op.drop_index(op.f('ix_prompt_classifications_session_id'), table_name='prompt_classifications')
    op.drop_index(op.f('ix_prompt_classifications_chat_history_id'), table_name='prompt_classifications')
    op.drop_table('prompt_classifications')
    # ### end Alembic commands ###
