"""fixing bug

Revision ID: 161334a26017
Revises: 22efa5f8f10e
Create Date: 2026-02-27 14:11:59.900018

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '161334a26017'
down_revision: Union[str, Sequence[str], None] = '22efa5f8f10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('class_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'class_id')
    # ### end Alembic commands ###
