"""update user table for course relation

Revision ID: 22efa5f8f10e
Revises: 9c75bc949602
Create Date: 2026-02-27 14:05:14.728817

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '22efa5f8f10e'
down_revision: Union[str, Sequence[str], None] = '9c75bc949602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
