"""bug fixing

Revision ID: 3a37441e136b
Revises: 983aaf8361db
Create Date: 2026-03-03 07:35:54.102274

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a37441e136b'
down_revision: Union[str, Sequence[str], None] = '983aaf8361db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chat_histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_column('chat_histories', 'user_id')
    # ### end Alembic commands ###
