"""update prompt classification  table

Revision ID: 3ec1223ba6d4
Revises: ee140583f10f
Create Date: 2026-04-03 14:24:51.037494

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3ec1223ba6d4'
down_revision: Union[str, Sequence[str], None] = 'ee140583f10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
