"""add: is_active to tasks

Revision ID: 44ff06d90018
Revises: ebc35151e384
Create Date: 2026-06-23 10:34:24.420829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ff06d90018'
down_revision: Union[str, Sequence[str], None] = 'ebc35151e384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with a server default so existing rows get a value.
    # Using TRUE ensures the column is non‑null for all current and future rows.
    op.add_column(
        'tasks',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('TRUE'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_active')
    # ### end Alembic commands ###
