"""add description column

Revision ID: 51b2fe79567c
Revises: a6f5f07f76b3
Create Date: 2026-02-27 15:52:08.279330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b2fe79567c'
down_revision: Union[str, Sequence[str], None] = 'a6f5f07f76b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'description')
    # ### end Alembic commands ###
