"""fix class table

Revision ID: 698a8c55d9ae
Revises: 51b2fe79567c
Create Date: 2026-02-27 16:00:32.694618

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '698a8c55d9ae'
down_revision: Union[str, Sequence[str], None] = '51b2fe79567c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('semester', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
