"""update academic domain table

Revision ID: 812964d54307
Revises: e91d6b37cc7c
Create Date: 2026-02-27 13:47:43.720357

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '812964d54307'
down_revision: Union[str, Sequence[str], None] = 'e91d6b37cc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.add_column('classes', sa.Column('course_id', sa.UUID(), nullable=False))
    op.add_column('classes', sa.Column('semester', sa.String(length=100), nullable=False))
    op.add_column('classes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('classes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.drop_constraint(op.f('classes_teacher_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('classes', 'updated_at')
    op.drop_column('classes', 'description')
    op.drop_column('classes', 'teacher_id')
    op.drop_column('classes', 'deleted_at')
    op.drop_column('classes', 'is_deleted')
    op.add_column('courses', sa.Column('teacher_id', sa.UUID(), nullable=False))
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('courses', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_courses_class_id'), table_name='courses')
    op.drop_constraint(op.f('courses_class_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'deleted_at')
    op.drop_column('courses', 'class_id')
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'is_deleted')
    op.add_column('enrollments', sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_enrollments_class_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_constraint(op.f('unique_student_class_enrollment'), 'enrollments', type_='unique')
    op.drop_column('enrollments', 'created_at')
    op.drop_column('enrollments', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('enrollments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('unique_student_class_enrollment'), 'enrollments', ['student_id', 'class_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_enrollments_class_id'), 'enrollments', ['class_id'], unique=False)
    op.drop_column('enrollments', 'enrolled_at')
    op.add_column('courses', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_class_id_fkey'), 'courses', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_courses_class_id'), 'courses', ['class_id'], unique=False)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('courses', 'is_active')
    op.drop_column('courses', 'teacher_id')
    op.add_column('classes', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_teacher_id_fkey'), 'classes', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.alter_column('classes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('classes', 'is_active')
    op.drop_column('classes', 'semester')
    op.drop_column('classes', 'course_id')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
