"""bug fixing

Revision ID: 983aaf8361db
Revises: 698a8c55d9ae
Create Date: 2026-03-03 04:27:57.639919

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '983aaf8361db'
down_revision: Union[str, Sequence[str], None] = '698a8c55d9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('classes_teacher_id_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'teacher_id')
    op.alter_column('enrollments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_unique_constraint('uq_student_class', 'enrollments', ['student_id', 'class_id'])
    op.drop_constraint(op.f('tasks_class_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_class_id_fkey'), 'tasks', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_student_class', 'enrollments', type_='unique')
    op.alter_column('enrollments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.add_column('classes', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('classes_teacher_id_fkey'), 'classes', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
