"""update class and user table

Revision ID: 9c75bc949602
Revises: 812964d54307
Create Date: 2026-02-27 13:59:57.472134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c75bc949602'
down_revision: Union[str, Sequence[str], None] = '812964d54307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('teacher_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'classes', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'teacher_id')
    # ### end Alembic commands ###
