"""fix: chat_sessions relation

Revision ID: c9905c328b95
Revises: f58a16464e88
Create Date: 2026-06-23 07:49:30.134232

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c9905c328b95'
down_revision: Union[str, Sequence[str], None] = 'f58a16464e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
