"""bug fixing

Revision ID: c9b57d421557
Revises: 3a37441e136b
Create Date: 2026-03-04 14:48:37.822006

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c9b57d421557'
down_revision: Union[str, Sequence[str], None] = '3a37441e136b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
