"""update session analytics  table

Revision ID: ee140583f10f
Revises: d68cd1697950
Create Date: 2026-03-12 07:32:19.722655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee140583f10f'
down_revision: Union[str, Sequence[str], None] = 'd68cd1697950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_histories', 'status',
               existing_type=postgresql.ENUM('COMPLETED', 'STREAMING', 'ABORTED', name='message_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_histories', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_histories', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_histories', 'latency_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('session_analytics', sa.Column('task_id', sa.UUID(), nullable=False))
    op.add_column('session_analytics', sa.Column('total_prompts', sa.Integer(), nullable=False, comment='Total number of messages sent by student in this session'))
    op.add_column('session_analytics', sa.Column('avg_prompt_length', sa.Float(), nullable=False, comment='Average character length of student prompts'))
    op.add_column('session_analytics', sa.Column('session_duration_seconds', sa.Integer(), nullable=False, comment='Duration from first message to last message in seconds'))
    op.add_column('session_analytics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('session_analytics', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_analytics', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_analytics', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'session_analytics', ['chat_session_id'])
    op.create_foreign_key(None, 'session_analytics', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_analytics', type_='foreignkey')
    op.drop_constraint(None, 'session_analytics', type_='unique')
    op.alter_column('session_analytics', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_analytics', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_analytics', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_analytics', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('session_analytics', 'updated_at')
    op.drop_column('session_analytics', 'session_duration_seconds')
    op.drop_column('session_analytics', 'avg_prompt_length')
    op.drop_column('session_analytics', 'total_prompts')
    op.drop_column('session_analytics', 'task_id')
    op.alter_column('chat_histories', 'latency_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('chat_histories', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('chat_histories', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('chat_histories', 'status',
               existing_type=postgresql.ENUM('COMPLETED', 'STREAMING', 'ABORTED', name='message_status_enum'),
               server_default=sa.text("'STREAMING'::message_status_enum"),
               existing_nullable=False)
    # ### end Alembic commands ###
